architecture: UNET-PDHG
data:
  dataset: Static Image Denoising Dataset
  original_dataset: https://abdokamel.github.io/sidd/
  patch_size: 256
  path: data/images
  random_seed_split: 42
  test_num_samples: 620
  train_num_samples: 9000
  val_num_samples: 620
device: cuda:0
evaluation:
  metrics:
  - SSIM
  - PSNR
noise:
  max_sigma: 0.5
  min_sigma: 0.1
  random_seed_noise: 97
others:
  save_dir: models
  save_epoch_local: 10
  save_epoch_wandb: 10000
  wandb_mode: online
pdhg:
  T_train: 128
  up_bound: 0
project_name: SIDD
training:
  batch_size: 1
  epochs: 10000
  learning_rate: 0.0001
  loss_function: MSELoss
  manual_seed: 42
  optimizer: Adam
unet:
  activation: LeakyReLU
  downsampling_kernel: &id001 !!python/tuple
  - 2
  - 2
  - 1
  downsampling_mode: max
  in_channels: 1
  init_filters: 8
  n_blocks: 2
  out_channels: 2
  upsampling_kernel: *id001
  upsampling_mode: linear_interpolation
